services:
  - type: web
    name: paytaksi-api
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PUBLIC_BASE_URL
        sync: false
      - key: API_BASE
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: PASSENGER_BOT_TOKEN
        sync: false
      - key: DRIVER_BOT_TOKEN
        sync: false
      - key: ADMIN_BOT_TOKEN
        sync: false
      - key: RUN_BOTS_IN_WEB
        value: "1"
      - key: ADMIN_USERNAME
        value: Ratik
      - key: ADMIN_PASSWORD
        value: "0123456789"

databases:
  - name: paytaksi-postgres
    plan: free
    databaseName: paytaksi
    user: paytaksi
