services:
  - type: web
    name: paytaksi-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run migrate && npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        value: "1326729201"
      - key: PUBLIC_BASE_URL
        sync: false
      - key: WEBHOOK_SECRET
        value: "paytaksi_bot"
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
