services:
  - type: web
    name: paytaksi-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.2.0
      - key: WEB_CONCURRENCY
        value: 1
